import React from 'react';
import { GameReducerAction } from '../../state/gameReducer';
import { EnvironmentalHazard, GameState, JobCard } from '../../types';

interface DevModeSystemsProps {
  gameState: GameState;
  dispatch: React.Dispatch<GameReducerAction>;
}

// Helper for ID generation outside component to avoid purity issues
const generateId = (prefix: string) => `${prefix}_${Date.now()}`;

export const DevModeSystems: React.FC<DevModeSystemsProps> = ({ gameState, dispatch }) => {
  // Time Controls
  const advanceTime = (ms: number) => {
    // Just a rough simulation of advancing time, dispatching logic would be handled by game loop usually
    // But we can force update the timestamp
    dispatch({
      type: 'UPDATE_STATE',
      payload: {
        time: {
          ...gameState.time,
          shiftTime: gameState.time.shiftTime + ms,
          totalPlayTime: gameState.time.totalPlayTime + ms,
        },
      },
    });
  };

  const nextShiftCycle = () => {
    dispatch({
      type: 'UPDATE_STATE',
      payload: {
        time: {
          ...gameState.time,
          shiftCycle: gameState.time.shiftCycle + 1,
          shiftTime: 0,
        },
      },
    });
  };

  // Hazard Controls
  const toggleHazard = (type: 'weather' | 'system_failure' | 'containment') => {
    // Check if hazard of this type exists
    const exists = gameState.activeHazards.find((h) => h.type === type);

    if (exists) {
      // Remove
      dispatch({
        type: 'UPDATE_STATE',
        payload: { activeHazards: gameState.activeHazards.filter((h) => h.id !== exists.id) },
      });
    } else {
      // Add generic
      const newHazard: EnvironmentalHazard = {
        id: generateId(type),
        type,
        name: `Test ${type}`,
        description: 'Dev mode generated hazard',
        duration: 1000 * 60 * 5, // 5 mins
        effects: { sanityDrain: 1 },
      };
      dispatch({
        type: 'UPDATE_STATE',
        payload: { activeHazards: [...gameState.activeHazards, newHazard] },
      });
    }
  };

  // Active Job Controls
  const completeJob = () => {
    if (!gameState.activeJob) return;
    // Trigger job completion logic - strictly speaking this might need a specific action type
    // if the reducer handles complex logic. For now, we might just nullify it and give rewards.
    dispatch({ type: 'COMPLETE_JOB', payload: { success: true } });
  };

  const generateJob = () => {
    const mockJob: JobCard = {
      id: generateId('job'),
      title: 'Dev Mode Test Job',
      description: 'A job generated by dev tools.',
      requirements: { tools: ['technicianToolbox'] },
      rewardXP: 100,
      timeLeft: 300000,
      totalTime: 300000,
    };
    dispatch({ type: 'START_JOB', payload: { job: mockJob } });
  };

  // Procurement
  const deliverOrders = () => {
    const deliveredOrders = gameState.procurement.orders.map((o) => ({
      ...o,
      status: 'DELIVERED' as const,
    }));
    dispatch({
      type: 'UPDATE_STATE',
      payload: { procurement: { ...gameState.procurement, orders: deliveredOrders } },
    });
  };

  return (
    <div className="space-y-6">
      {/* Time & World */}
      <section className="bg-emerald-950/30 p-4 border border-emerald-800">
        <h2 className="text-lg font-bold text-emerald-400 mb-4 border-b border-emerald-800 pb-2">
          ⏰ Time & World
        </h2>

        <div className="grid grid-cols-2 gap-4 mb-4">
          <div>
            <p className="text-emerald-500 text-xs uppercase">Shift Time</p>
            <p className="text-emerald-300 font-mono text-lg">
              {(gameState.time.shiftTime / 1000 / 60).toFixed(1)} mins
            </p>
          </div>
          <div>
            <p className="text-emerald-500 text-xs uppercase">Shift Cycle</p>
            <p className="text-emerald-300 font-mono text-lg text-bold">
              {gameState.time.shiftCycle}
            </p>
          </div>
        </div>

        <div className="flex flex-wrap gap-2 mb-4">
          <button onClick={() => advanceTime(1000 * 60 * 15)} className="btn-dev-action">
            +15 Mins
          </button>
          <button onClick={() => advanceTime(1000 * 60 * 60)} className="btn-dev-action">
            +1 Hour
          </button>
          <button
            onClick={nextShiftCycle}
            className="btn-dev-action border-yellow-700 text-yellow-500"
          >
            Next Shift
          </button>
        </div>
      </section>

      {/* Hazards */}
      <section className="bg-emerald-950/30 p-4 border border-emerald-800">
        <h2 className="text-lg font-bold text-emerald-400 mb-4 border-b border-emerald-800 pb-2">
          ⚠️ Active Hazards
        </h2>
        <div className="flex gap-2">
          {(['weather', 'system_failure', 'containment'] as const).map((type) => {
            const isActive = gameState.activeHazards.some((h) => h.type === type);
            return (
              <button
                key={type}
                onClick={() => toggleHazard(type)}
                className={`px-3 py-2 text-xs border font-bold uppercase ${isActive ? 'bg-red-900/50 border-red-500 text-red-200' : 'bg-emerald-950 border-emerald-800 text-emerald-600'}`}
              >
                {type.replace('_', ' ')}
              </button>
            );
          })}
        </div>
      </section>

      {/* Active Job */}
      <section className="bg-emerald-950/30 p-4 border border-emerald-800">
        <h2 className="text-lg font-bold text-emerald-400 mb-4 border-b border-emerald-800 pb-2">
          📋 Active Job
        </h2>
        {gameState.activeJob ? (
          <div className="mb-4">
            <p className="text-emerald-300 font-bold">{gameState.activeJob.title}</p>
            <p className="text-emerald-500 text-xs mb-2">{gameState.activeJob.description}</p>
            <div className="flex gap-2">
              <button
                onClick={completeJob}
                className="bg-emerald-700 hover:bg-emerald-600 text-white text-xs px-3 py-1 rounded"
              >
                Force Complete
              </button>
              <button
                onClick={() => dispatch({ type: 'UPDATE_STATE', payload: { activeJob: null } })}
                className="bg-red-900/50 text-red-200 text-xs px-3 py-1 rounded"
              >
                Cancel
              </button>
            </div>
          </div>
        ) : (
          <div>
            <p className="text-emerald-600 italic mb-2">No active job</p>
            <button
              onClick={generateJob}
              className="bg-emerald-800/50 text-emerald-300 text-xs px-3 py-1 border border-emerald-600"
            >
              Generate Test Job
            </button>
          </div>
        )}
      </section>

      {/* Procurement */}
      <section className="bg-emerald-950/30 p-4 border border-emerald-800">
        <h2 className="text-lg font-bold text-emerald-400 mb-4 border-b border-emerald-800 pb-2">
          📦 Procurement
        </h2>
        <p className="text-emerald-500 text-xs mb-2">
          Pending Orders:{' '}
          {gameState.procurement.orders.filter((o) => o.status !== 'DELIVERED').length}
        </p>
        <button
          onClick={deliverOrders}
          className="w-full bg-emerald-900/40 hover:bg-emerald-800 border border-emerald-600 text-emerald-300 py-1 text-sm"
        >
          Force Deliver All
        </button>
      </section>
    </div>
  );
};
